// Generated by IcedCoffeeScript 1.6.2d
(function() {
  var GPlusAPI, api, col, crc32, db, fetch, fs, iced, jsdom, main, make_esc, mongo, request, _, __iced_k, __iced_k_noop,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  make_esc = require('iced-error').make_esc;

  jsdom = require('jsdom');

  fs = require('fs');

  request = require('request');

  crc32 = require('crc').crc32;

  mongo = require('mongoskin');

  _ = require('underscore');

  global.CONFIG = JSON.parse(fs.readFileSync('config.json'));

  GPlusAPI = require('./lib/api');

  api = new GPlusAPI(CONFIG.refresh_token, '107023756258778911982');

  db = mongo.db(CONFIG.mongodb, {
    w: true
  });

  col = db.collection('updates');

  fetch = function(gcb) {
    var $, e, esc, html, item, list, req, window, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    esc = make_esc(gcb);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "main.coffee",
        funcname: "fetch"
      });
      request({
        url: 'http://zh.moegirl.org/api.php',
        qs: {
          format: 'json',
          action: 'parse',
          page: 'User:萌星空/你知道吗/存档/更新姬版',
          prop: 'text'
        },
        method: 'GET',
        timeout: 5000,
        headers: {
          'User-Agent': 'Node.js'
        }
      }, esc(__iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return req = arguments[0];
          };
        })(),
        lineno: 31
      })));
      __iced_deferrals._fulfill();
    })(function() {
      if (req.statusCode === !200) {
        return gcb(req.statusCode);
      }
      html = '';
      try {
        html = JSON.parse(req.body).parse.text['*'];
      } catch (_error) {
        e = _error;
        return gcb(e);
      }
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "main.coffee",
          funcname: "fetch"
        });
        jsdom.env(html, ['jquery.js'], {}, esc(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return window = arguments[0];
            };
          })(),
          lineno: 41
        })));
        __iced_deferrals._fulfill();
      })(function() {
        $ = window.$;
        $('table').remove();
        list = (function() {
          var _i, _len, _ref, _results;
          _ref = $('li');
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            _results.push({
              title: $.trim($(item).text().split('——')[0]),
              url: 'http://zh.moegirl.org' + $(item).children('a:last').attr('href'),
              "new": $(item).children('a:last').hasClass('new')
            });
          }
          return _results;
        })();
        return gcb(null, list);
      });
    });
  };

  main = function(gcb) {
    var activity, embed, esc, hash, i, item, list, results, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    esc = make_esc(gcb);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "main.coffee",
        funcname: "main"
      });
      fetch(esc(__iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return list = arguments[0];
          };
        })(),
        lineno: 53
      })));
      __iced_deferrals._fulfill();
    })(function() {
      var _i, _len;
      hash = [];
      for (i = _i = 0, _len = list.length; _i < _len; i = ++_i) {
        item = list[i];
        item.hash = crc32(item.title);
        list[i].hash = item.hash;
        hash.push(item.hash);
      }
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "main.coffee",
          funcname: "main"
        });
        col.find({
          hash: {
            '$in': hash
          }
        }, {
          _id: 0,
          hash: 1
        }).toArray(esc(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return results = arguments[0];
            };
          })(),
          lineno: 61
        })));
        __iced_deferrals._fulfill();
      })(function() {
        if (list.length === results.length) {
          return gcb(null, 'nothing to post');
        }
        results = _.flatten(results.map(function(item) {
          return item.hash;
        }));
        item = _.find(list, function(item) {
          var _ref;
          return _ref = item.hash, __indexOf.call(results, _ref) < 0;
        });
        if (item == null) {
          return gcb(null, 'nothing to post');
        }
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "main.coffee",
            funcname: "main"
          });
          api.linkPreview(item.url, esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return embed = arguments[0];
              };
            })(),
            lineno: 68
          })));
          __iced_deferrals._fulfill();
        })(function() {
          if (!embed.succeeded) {
            return gcb(new Error("Cannot fetch " + item.url + " from Google server."));
          }
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "main.coffee",
              funcname: "main"
            });
            api.postPublicActivity(item.title, embed.embedItem[0], esc(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return activity = arguments[0];
                };
              })(),
              lineno: 72
            })));
            __iced_deferrals._fulfill();
          })(function() {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "main.coffee",
                funcname: "main"
              });
              col.insert(item, esc(__iced_deferrals.defer({
                lineno: 74
              })));
              __iced_deferrals._fulfill();
            })(function() {
              return gcb(null, activity, item);
            });
          });
        });
      });
    });
  };

  setInterval(function() {
    return main(function(err, a, i) {
      if (err) {
        return require('util').log("[ERROR]" + err);
      }
      return require('util').log("[POSTED]" + a.stream.update[0].updateId + "(" + i.hash + ")");
    });
  }, 3600000);

}).call(this);
