// Generated by IcedCoffeeScript 1.6.2d
(function() {
  var make_errors;



  make_errors = require('iced-error').make_errors;

  exports.E = make_errors({
    NETWORK_FAIL: 'Network connection may down.Cannot connect to the server.',
    CREDIT_ERROR: 'The given refresh_token is illegal.',
    INVALID_JSON: 'Cannot parse the response JSON.'
  });

}).call(this);
